# PHP
# Test and package your PHP project.
# Add steps that run tests, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/php

trigger:
- Develop

#pool:
#  vmImage: ubuntu-latest

variables:
  archives_path: 'C:\wamp64\www\'
  phpVersion: 7.3
  npmVersion: 2.182

steps:
- script: |
    sudo update-alternatives --set php /usr/bin/php$(phpVersion)
    sudo update-alternatives --set phar /usr/bin/phar$(phpVersion)
    sudo update-alternatives --set phpdbg /usr/bin/phpdbg$(phpVersion)
    sudo update-alternatives --set php-cgi /usr/bin/php-cgi$(phpVersion)
    sudo update-alternatives --set phar.phar /usr/bin/phar.phar$(phpVersion)
    php -version
  displayName: 'Use PHP version $(phpVersion)'

- script: composer install --no-intercation --prefer-dist
  workingDirectory: $
  displayName: 'composer install'

- task: Npm@1
  inputs:
    command: 'install'

- task: Npm@1
  inputs:
    command: 'custom'
    workingDir: $
    customCommand: 'run prod'

- task: ArchiveFiles@2
  displayName: 'Archive files'
  inputs:
    rootFolderOrFile: $
    includeRootFolder: false
    archiveType: tar
    archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
    replaceExistingArchive: true

- task: CopyFilesOverSSH@0
  inputs:
    sshEndpoint: '80.92.87.58'
    contents: 'testarchive.tar.gz'
    readyTimeout: '20000'

- task: SSH@0
  inputs:
    sshEndpoint: Remote-server
    runOptions: 'commands'
    commands: 'tar –xvzf testarchive.gz'
    readyTimeout: '20000'
