# PHP
# Test and package your PHP project.
# Add steps that run tests, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/php

trigger:
- main

# pool:
#  vmImage: ubuntu-latest

variables:
  phpVersion: 7.3
  path: C:\wamp64\www

steps:
- script: |
    sudo update-alternatives --set php /usr/bin/php$(phpVersion)
    sudo update-alternatives --set phar /usr/bin/phar$(phpVersion)
    sudo update-alternatives --set phpdbg /usr/bin/phpdbg$(phpVersion)
    sudo update-alternatives --set php-cgi /usr/bin/php-cgi$(phpVersion)
    sudo update-alternatives --set phar.phar /usr/bin/phar.phar$(phpVersion)
    php -version
  displayName: 'Use PHP version $(phpVersion)'

- script: composer install --no-interaction --prefer-dist
  displayName: 'composer install'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(path)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(path)\test\testarchive.zip'
    replaceExistingArchive: true
    verbose: true

- task: ExtractFiles@1
  inputs:
    archiveFilePatterns: 'test-dev/$(path)\test\testarchive.zip'
    destinationFolder: '$(path)\test-dev'
    cleanDestinationFolder: true
    overwriteExistingFiles: true
